// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AcceptEncoding.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SWGOH.Models.Protocols {

  /// <summary>Holder for reflection information generated from AcceptEncoding.proto</summary>
  public static partial class AcceptEncodingReflection {

    #region Descriptor
    /// <summary>File descriptor for AcceptEncoding.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AcceptEncodingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBY2NlcHRFbmNvZGluZy5wcm90bxIWU1dHT0guTW9kZWxzLlByb3RvY29s",
            "cypDCg5BY2NlcHRFbmNvZGluZxIZChVERUZBVUxUQUNDRVBURU5DT0RJTkcQ",
            "ARIWChJHWklQQUNDRVBURU5DT0RJTkcQAg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SWGOH.Models.Protocols.AcceptEncoding), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum AcceptEncoding {
    [pbr::OriginalName("DEFAULTACCEPTENCODING")] Defaultacceptencoding = 1,
    [pbr::OriginalName("GZIPACCEPTENCODING")] Gzipacceptencoding = 2,
  }

  #endregion

}

#endregion Designer generated code
