// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ContentEncoding.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SWGOH.Models.Protocols {

  /// <summary>Holder for reflection information generated from ContentEncoding.proto</summary>
  public static partial class ContentEncodingReflection {

    #region Descriptor
    /// <summary>File descriptor for ContentEncoding.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContentEncodingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVDb250ZW50RW5jb2RpbmcucHJvdG8SFlNXR09ILk1vZGVscy5Qcm90b2Nv",
            "bHMqRgoPQ29udGVudEVuY29kaW5nEhoKFkRFRkFVTFRDT05URU5URU5DT0RJ",
            "TkcQABIXChNHWklQQ09OVEVOVEVOQ09ESU5HEAE="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SWGOH.Models.Protocols.ContentEncoding), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ContentEncoding {
    [pbr::OriginalName("DEFAULTCONTENTENCODING")] Defaultcontentencoding = 0,
    [pbr::OriginalName("GZIPCONTENTENCODING")] Gzipcontentencoding = 1,
  }

  #endregion

}

#endregion Designer generated code
