// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResponseCode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SWGOH.Models.Protocols {

  /// <summary>Holder for reflection information generated from ResponseCode.proto</summary>
  public static partial class ResponseCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for ResponseCode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJSZXNwb25zZUNvZGUucHJvdG8SFlNXR09ILk1vZGVscy5Qcm90b2NvbHMq",
            "7AQKDFJlc3BvbnNlQ29kZRIICgROT05FEAASBgoCT0sQARIJCgVFUlJPUhAC",
            "Eg8KC1NFUlZFUkVSUk9SEAMSEgoOU0VTU0lPTkVYUElSRUQQBBIOCgpBVVRI",
            "RkFJTEVEEAUSEAoMUkFURUVYQ0VFREVEEAYSFQoRU0VSVkVSVU5BVkFJTEFC",
            "TEUQBxISCg5JTlZBTElEUkVRVUVTVBAIEg8KC0lOVkFMSUREQVRBEAkSHwob",
            "TEVBREVSQk9BUkRNQVRDSE1BS0lOR0VSUk9SEAoSEAoMVU5BVVRIT1JJWkVE",
            "EAsSDQoJU1VTUEVOREVEEAwSEAoMU0VSVkVST1VUQUdFEA0SFgoSTkVUV09S",
            "S1VOQVZBSUxBQkxFEBQSEAoMU0VRVUVOQ0VISUdIEB4SDwoLU0VRVUVOQ0VM",
            "T1cQHxISCg5SRUNPUkROT1RGT1VORBAgEhEKDUVWRU5UTk9URk9VTkQQIRIZ",
            "ChVJTlNVRkZJQ0lFTlRSRVNPVVJDRVMQKBIYChRJTlZBTElEQ0xJRU5UVkVS",
            "U0lPThAyEhYKEkZPUkNFQ0xJRU5UUkVTVEFSVBAzEhYKEklOQ09NUEFUSUJM",
            "RURFVklDRRA0EhIKDkFDQ09VTlRVUERBVEVEEDUSEgoOSU5WQUxJRFJFQ0VJ",
            "UFQQPBISCg5QQVlNRU5UUEVORElORxA9EhQKEE9QUE9ORU5USU5CQVRUTEUQ",
            "RxIPCgtVTkRFUkFUVEFDSxBIEhUKEU9QUE9ORU5UREFUQVNUQUxFEEkSEgoO",
            "QkFUVExFVElNRURPVVQQShITCg9QTEFZRVJSQU5LU1RBTEUQSw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SWGOH.Models.Protocols.ResponseCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ResponseCode {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("OK")] Ok = 1,
    [pbr::OriginalName("ERROR")] Error = 2,
    [pbr::OriginalName("SERVERERROR")] Servererror = 3,
    [pbr::OriginalName("SESSIONEXPIRED")] Sessionexpired = 4,
    [pbr::OriginalName("AUTHFAILED")] Authfailed = 5,
    [pbr::OriginalName("RATEEXCEEDED")] Rateexceeded = 6,
    [pbr::OriginalName("SERVERUNAVAILABLE")] Serverunavailable = 7,
    [pbr::OriginalName("INVALIDREQUEST")] Invalidrequest = 8,
    [pbr::OriginalName("INVALIDDATA")] Invaliddata = 9,
    /// <summary>
    /// 0x0000000A
    /// </summary>
    [pbr::OriginalName("LEADERBOARDMATCHMAKINGERROR")] Leaderboardmatchmakingerror = 10,
    /// <summary>
    /// 0x0000000B
    /// </summary>
    [pbr::OriginalName("UNAUTHORIZED")] Unauthorized = 11,
    /// <summary>
    /// 0x0000000C
    /// </summary>
    [pbr::OriginalName("SUSPENDED")] Suspended = 12,
    /// <summary>
    /// 0x0000000D
    /// </summary>
    [pbr::OriginalName("SERVEROUTAGE")] Serveroutage = 13,
    /// <summary>
    /// 0x00000014
    /// </summary>
    [pbr::OriginalName("NETWORKUNAVAILABLE")] Networkunavailable = 20,
    /// <summary>
    /// 0x0000001E
    /// </summary>
    [pbr::OriginalName("SEQUENCEHIGH")] Sequencehigh = 30,
    /// <summary>
    /// 0x0000001F
    /// </summary>
    [pbr::OriginalName("SEQUENCELOW")] Sequencelow = 31,
    /// <summary>
    /// 0x00000020
    /// </summary>
    [pbr::OriginalName("RECORDNOTFOUND")] Recordnotfound = 32,
    /// <summary>
    /// 0x00000021
    /// </summary>
    [pbr::OriginalName("EVENTNOTFOUND")] Eventnotfound = 33,
    /// <summary>
    /// 0x00000028
    /// </summary>
    [pbr::OriginalName("INSUFFICIENTRESOURCES")] Insufficientresources = 40,
    /// <summary>
    /// 0x00000032
    /// </summary>
    [pbr::OriginalName("INVALIDCLIENTVERSION")] Invalidclientversion = 50,
    /// <summary>
    /// 0x00000033
    /// </summary>
    [pbr::OriginalName("FORCECLIENTRESTART")] Forceclientrestart = 51,
    /// <summary>
    /// 0x00000034
    /// </summary>
    [pbr::OriginalName("INCOMPATIBLEDEVICE")] Incompatibledevice = 52,
    /// <summary>
    /// 0x00000035
    /// </summary>
    [pbr::OriginalName("ACCOUNTUPDATED")] Accountupdated = 53,
    /// <summary>
    /// 0x0000003C
    /// </summary>
    [pbr::OriginalName("INVALIDRECEIPT")] Invalidreceipt = 60,
    /// <summary>
    /// 0x0000003D
    /// </summary>
    [pbr::OriginalName("PAYMENTPENDING")] Paymentpending = 61,
    /// <summary>
    /// 0x00000047
    /// </summary>
    [pbr::OriginalName("OPPONENTINBATTLE")] Opponentinbattle = 71,
    /// <summary>
    /// 0x00000048
    /// </summary>
    [pbr::OriginalName("UNDERATTACK")] Underattack = 72,
    /// <summary>
    /// 0x00000049
    /// </summary>
    [pbr::OriginalName("OPPONENTDATASTALE")] Opponentdatastale = 73,
    /// <summary>
    /// 0x0000004A
    /// </summary>
    [pbr::OriginalName("BATTLETIMEDOUT")] Battletimedout = 74,
    /// <summary>
    /// 0x0000004B
    /// </summary>
    [pbr::OriginalName("PLAYERRANKSTALE")] Playerrankstale = 75,
  }

  #endregion

}

#endregion Designer generated code
