// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StoreRpcBuyItemResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SWGOH.Models.Protocols {

  /// <summary>Holder for reflection information generated from StoreRpcBuyItemResponse.proto</summary>
  public static partial class StoreRpcBuyItemResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for StoreRpcBuyItemResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StoreRpcBuyItemResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1TdG9yZVJwY0J1eUl0ZW1SZXNwb25zZS5wcm90bxIWU1dHT0guTW9kZWxz",
            "LlByb3RvY29scyLhAQoXU3RvcmVScGNCdXlJdGVtUmVzcG9uc2USOQoEaXRl",
            "bRgBIAEoCzIrLlNXR09ILk1vZGVscy5Qcm90b2NvbHMuU3RvcmVScGNCdXlJ",
            "dGVtSXRlbRIOCgNrZXkYAiABKAM6ATASEwoIdW5rbm93bjEYBSABKAM6ATAS",
            "EgoIdW5rbm93bjIYBiABKAk6ABITCgh1bmtub3duMxgHIAEoAzoBMBI9CgZw",
            "bGF5ZXIYCCABKAsyLS5TV0dPSC5Nb2RlbHMuUHJvdG9jb2xzLlN0b3JlUnBj",
            "QnV5SXRlbVBsYXllciKNAQoTU3RvcmVScGNCdXlJdGVtSXRlbRJDCgdwcm9k",
            "dWN0GAEgASgLMjIuU1dHT0guTW9kZWxzLlByb3RvY29scy5TdG9yZVJwY0J1",
            "eUl0ZW1JdGVtUHJvZHVjdBIhCgRwYWNrGAQgASgJOhNwcmVtaXVtLXBhY2st",
            "c2lsdmVyEg4KA2tleRgGIAEoAzoBOSKwAgoaU3RvcmVScGNCdXlJdGVtSXRl",
            "bVByb2R1Y3QSSAoGY3JlZGl0GAEgASgLMjguU1dHT0guTW9kZWxzLlByb3Rv",
            "Y29scy5TdG9yZVJwY0J1eUl0ZW1JdGVtUHJvZHVjdENyZWRpdBJOCgl1bml0",
            "c2hhcmQYBCABKAsyOy5TV0dPSC5Nb2RlbHMuUHJvdG9jb2xzLlN0b3JlUnBj",
            "QnV5SXRlbUl0ZW1Qcm9kdWN0VW5pdHNoYXJkEk4KCWdlYXJzaGFyZBgNIAEo",
            "CzI7LlNXR09ILk1vZGVscy5Qcm90b2NvbHMuU3RvcmVScGNCdXlJdGVtSXRl",
            "bVByb2R1Y3RHZWFyc2hhcmQSEwoIdW5rbm93bjEYEiABKAM6ATASEwoIdW5r",
            "bm93bjIYGSABKAM6ATAiXAogU3RvcmVScGNCdXlJdGVtSXRlbVByb2R1Y3RD",
            "cmVkaXQSDwoEbmFtZRgBIAEoAzoBMRITCghxdWFudGl0eRgCIAEoAzoBMBIS",
            "Cgd1bmtub3duGAMgASgDOgEwIl4KI1N0b3JlUnBjQnV5SXRlbUl0ZW1Qcm9k",
            "dWN0VW5pdHNoYXJkEg4KBG5hbWUYASABKAk6ABITCghxdWFudGl0eRgCIAEo",
            "AzoBMBISCgd1bmtub3duGAMgASgDOgEwIl4KI1N0b3JlUnBjQnV5SXRlbUl0",
            "ZW1Qcm9kdWN0R2VhcnNoYXJkEg4KBG5hbWUYASABKAk6ABITCghxdWFudGl0",
            "eRgCIAEoAzoBMBISCgd1bmtub3duGAMgASgDOgEwIicKFVN0b3JlUnBjQnV5",
            "SXRlbVBsYXllchIOCgRuYW1lGAcgASgJOgA="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemResponse), global::SWGOH.Models.Protocols.StoreRpcBuyItemResponse.Parser, new[]{ "Item", "Key", "Unknown1", "Unknown2", "Unknown3", "Player" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemItem), global::SWGOH.Models.Protocols.StoreRpcBuyItemItem.Parser, new[]{ "Product", "Pack", "Key" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct), global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct.Parser, new[]{ "Credit", "Unitshard", "Gearshard", "Unknown1", "Unknown2" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit), global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit.Parser, new[]{ "Name", "Quantity", "Unknown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard), global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard.Parser, new[]{ "Name", "Quantity", "Unknown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard), global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard.Parser, new[]{ "Name", "Quantity", "Unknown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer), global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer.Parser, new[]{ "Name" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StoreRpcBuyItemResponse : pb::IMessage<StoreRpcBuyItemResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemResponse> _parser = new pb::MessageParser<StoreRpcBuyItemResponse>(() => new StoreRpcBuyItemResponse());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemResponse(StoreRpcBuyItemResponse other) : this() {
      _hasBits0 = other._hasBits0;
      item_ = other.item_ != null ? other.item_.Clone() : null;
      key_ = other.key_;
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      unknown3_ = other.unknown3_;
      player_ = other.player_ != null ? other.player_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemResponse Clone() {
      return new StoreRpcBuyItemResponse(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemItem item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemItem Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private readonly static long KeyDefaultValue = 0L;

    private long key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Key {
      get { if ((_hasBits0 & 1) != 0) { return key_; } else { return KeyDefaultValue; } }
      set {
        _hasBits0 |= 1;
        key_ = value;
      }
    }
    /// <summary>Gets whether the "key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasKey {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearKey() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 5;
    private readonly static long Unknown1DefaultValue = 0L;

    private long unknown1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown1 {
      get { if ((_hasBits0 & 2) != 0) { return unknown1_; } else { return Unknown1DefaultValue; } }
      set {
        _hasBits0 |= 2;
        unknown1_ = value;
      }
    }
    /// <summary>Gets whether the "unknown1" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown1 {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "unknown1" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown1() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 6;
    private readonly static string Unknown2DefaultValue = "";

    private string unknown2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Unknown2 {
      get { return unknown2_ ?? Unknown2DefaultValue; }
      set {
        unknown2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "unknown2" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown2 {
      get { return unknown2_ != null; }
    }
    /// <summary>Clears the value of the "unknown2" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown2() {
      unknown2_ = null;
    }

    /// <summary>Field number for the "unknown3" field.</summary>
    public const int Unknown3FieldNumber = 7;
    private readonly static long Unknown3DefaultValue = 0L;

    private long unknown3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown3 {
      get { if ((_hasBits0 & 4) != 0) { return unknown3_; } else { return Unknown3DefaultValue; } }
      set {
        _hasBits0 |= 4;
        unknown3_ = value;
      }
    }
    /// <summary>Gets whether the "unknown3" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown3 {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "unknown3" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown3() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 8;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer player_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      if (Key != other.Key) return false;
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      if (Unknown3 != other.Unknown3) return false;
      if (!object.Equals(Player, other.Player)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      if (HasKey) hash ^= Key.GetHashCode();
      if (HasUnknown1) hash ^= Unknown1.GetHashCode();
      if (HasUnknown2) hash ^= Unknown2.GetHashCode();
      if (HasUnknown3) hash ^= Unknown3.GetHashCode();
      if (player_ != null) hash ^= Player.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (HasKey) {
        output.WriteRawTag(16);
        output.WriteInt64(Key);
      }
      if (HasUnknown1) {
        output.WriteRawTag(40);
        output.WriteInt64(Unknown1);
      }
      if (HasUnknown2) {
        output.WriteRawTag(50);
        output.WriteString(Unknown2);
      }
      if (HasUnknown3) {
        output.WriteRawTag(56);
        output.WriteInt64(Unknown3);
      }
      if (player_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Player);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (HasKey) {
        output.WriteRawTag(16);
        output.WriteInt64(Key);
      }
      if (HasUnknown1) {
        output.WriteRawTag(40);
        output.WriteInt64(Unknown1);
      }
      if (HasUnknown2) {
        output.WriteRawTag(50);
        output.WriteString(Unknown2);
      }
      if (HasUnknown3) {
        output.WriteRawTag(56);
        output.WriteInt64(Unknown3);
      }
      if (player_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Player);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (HasKey) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Key);
      }
      if (HasUnknown1) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown1);
      }
      if (HasUnknown2) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Unknown2);
      }
      if (HasUnknown3) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown3);
      }
      if (player_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemResponse other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItem();
        }
        Item.MergeFrom(other.Item);
      }
      if (other.HasKey) {
        Key = other.Key;
      }
      if (other.HasUnknown1) {
        Unknown1 = other.Unknown1;
      }
      if (other.HasUnknown2) {
        Unknown2 = other.Unknown2;
      }
      if (other.HasUnknown3) {
        Unknown3 = other.Unknown3;
      }
      if (other.player_ != null) {
        if (player_ == null) {
          Player = new global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer();
        }
        Player.MergeFrom(other.Player);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItem();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            Key = input.ReadInt64();
            break;
          }
          case 40: {
            Unknown1 = input.ReadInt64();
            break;
          }
          case 50: {
            Unknown2 = input.ReadString();
            break;
          }
          case 56: {
            Unknown3 = input.ReadInt64();
            break;
          }
          case 66: {
            if (player_ == null) {
              Player = new global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer();
            }
            input.ReadMessage(Player);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItem();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            Key = input.ReadInt64();
            break;
          }
          case 40: {
            Unknown1 = input.ReadInt64();
            break;
          }
          case 50: {
            Unknown2 = input.ReadString();
            break;
          }
          case 56: {
            Unknown3 = input.ReadInt64();
            break;
          }
          case 66: {
            if (player_ == null) {
              Player = new global::SWGOH.Models.Protocols.StoreRpcBuyItemPlayer();
            }
            input.ReadMessage(Player);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemItem : pb::IMessage<StoreRpcBuyItemItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemItem> _parser = new pb::MessageParser<StoreRpcBuyItemItem>(() => new StoreRpcBuyItemItem());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItem(StoreRpcBuyItemItem other) : this() {
      _hasBits0 = other._hasBits0;
      product_ = other.product_ != null ? other.product_.Clone() : null;
      pack_ = other.pack_;
      key_ = other.key_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItem Clone() {
      return new StoreRpcBuyItemItem(this);
    }

    /// <summary>Field number for the "product" field.</summary>
    public const int ProductFieldNumber = 1;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct product_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct Product {
      get { return product_; }
      set {
        product_ = value;
      }
    }

    /// <summary>Field number for the "pack" field.</summary>
    public const int PackFieldNumber = 4;
    private readonly static string PackDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("cHJlbWl1bS1wYWNrLXNpbHZlcg=="), 0, 19);

    private string pack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Pack {
      get { return pack_ ?? PackDefaultValue; }
      set {
        pack_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "pack" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPack {
      get { return pack_ != null; }
    }
    /// <summary>Clears the value of the "pack" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPack() {
      pack_ = null;
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 6;
    private readonly static long KeyDefaultValue = 9L;

    private long key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Key {
      get { if ((_hasBits0 & 1) != 0) { return key_; } else { return KeyDefaultValue; } }
      set {
        _hasBits0 |= 1;
        key_ = value;
      }
    }
    /// <summary>Gets whether the "key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasKey {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearKey() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Product, other.Product)) return false;
      if (Pack != other.Pack) return false;
      if (Key != other.Key) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (product_ != null) hash ^= Product.GetHashCode();
      if (HasPack) hash ^= Pack.GetHashCode();
      if (HasKey) hash ^= Key.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (product_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Product);
      }
      if (HasPack) {
        output.WriteRawTag(34);
        output.WriteString(Pack);
      }
      if (HasKey) {
        output.WriteRawTag(48);
        output.WriteInt64(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (product_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Product);
      }
      if (HasPack) {
        output.WriteRawTag(34);
        output.WriteString(Pack);
      }
      if (HasKey) {
        output.WriteRawTag(48);
        output.WriteInt64(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (product_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Product);
      }
      if (HasPack) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pack);
      }
      if (HasKey) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Key);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemItem other) {
      if (other == null) {
        return;
      }
      if (other.product_ != null) {
        if (product_ == null) {
          Product = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct();
        }
        Product.MergeFrom(other.Product);
      }
      if (other.HasPack) {
        Pack = other.Pack;
      }
      if (other.HasKey) {
        Key = other.Key;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (product_ == null) {
              Product = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct();
            }
            input.ReadMessage(Product);
            break;
          }
          case 34: {
            Pack = input.ReadString();
            break;
          }
          case 48: {
            Key = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (product_ == null) {
              Product = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProduct();
            }
            input.ReadMessage(Product);
            break;
          }
          case 34: {
            Pack = input.ReadString();
            break;
          }
          case 48: {
            Key = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemItemProduct : pb::IMessage<StoreRpcBuyItemItemProduct>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemItemProduct> _parser = new pb::MessageParser<StoreRpcBuyItemItemProduct>(() => new StoreRpcBuyItemItemProduct());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemItemProduct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProduct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProduct(StoreRpcBuyItemItemProduct other) : this() {
      _hasBits0 = other._hasBits0;
      credit_ = other.credit_ != null ? other.credit_.Clone() : null;
      unitshard_ = other.unitshard_ != null ? other.unitshard_.Clone() : null;
      gearshard_ = other.gearshard_ != null ? other.gearshard_.Clone() : null;
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProduct Clone() {
      return new StoreRpcBuyItemItemProduct(this);
    }

    /// <summary>Field number for the "credit" field.</summary>
    public const int CreditFieldNumber = 1;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit credit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit Credit {
      get { return credit_; }
      set {
        credit_ = value;
      }
    }

    /// <summary>Field number for the "unitshard" field.</summary>
    public const int UnitshardFieldNumber = 4;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard unitshard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard Unitshard {
      get { return unitshard_; }
      set {
        unitshard_ = value;
      }
    }

    /// <summary>Field number for the "gearshard" field.</summary>
    public const int GearshardFieldNumber = 13;
    private global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard gearshard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard Gearshard {
      get { return gearshard_; }
      set {
        gearshard_ = value;
      }
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 18;
    private readonly static long Unknown1DefaultValue = 0L;

    private long unknown1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown1 {
      get { if ((_hasBits0 & 1) != 0) { return unknown1_; } else { return Unknown1DefaultValue; } }
      set {
        _hasBits0 |= 1;
        unknown1_ = value;
      }
    }
    /// <summary>Gets whether the "unknown1" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown1 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "unknown1" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown1() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 25;
    private readonly static long Unknown2DefaultValue = 0L;

    private long unknown2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown2 {
      get { if ((_hasBits0 & 2) != 0) { return unknown2_; } else { return Unknown2DefaultValue; } }
      set {
        _hasBits0 |= 2;
        unknown2_ = value;
      }
    }
    /// <summary>Gets whether the "unknown2" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown2 {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "unknown2" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown2() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemItemProduct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemItemProduct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Credit, other.Credit)) return false;
      if (!object.Equals(Unitshard, other.Unitshard)) return false;
      if (!object.Equals(Gearshard, other.Gearshard)) return false;
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (credit_ != null) hash ^= Credit.GetHashCode();
      if (unitshard_ != null) hash ^= Unitshard.GetHashCode();
      if (gearshard_ != null) hash ^= Gearshard.GetHashCode();
      if (HasUnknown1) hash ^= Unknown1.GetHashCode();
      if (HasUnknown2) hash ^= Unknown2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (credit_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Credit);
      }
      if (unitshard_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Unitshard);
      }
      if (gearshard_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Gearshard);
      }
      if (HasUnknown1) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(Unknown1);
      }
      if (HasUnknown2) {
        output.WriteRawTag(200, 1);
        output.WriteInt64(Unknown2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (credit_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Credit);
      }
      if (unitshard_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Unitshard);
      }
      if (gearshard_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Gearshard);
      }
      if (HasUnknown1) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(Unknown1);
      }
      if (HasUnknown2) {
        output.WriteRawTag(200, 1);
        output.WriteInt64(Unknown2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (credit_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Credit);
      }
      if (unitshard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unitshard);
      }
      if (gearshard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gearshard);
      }
      if (HasUnknown1) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Unknown1);
      }
      if (HasUnknown2) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Unknown2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemItemProduct other) {
      if (other == null) {
        return;
      }
      if (other.credit_ != null) {
        if (credit_ == null) {
          Credit = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit();
        }
        Credit.MergeFrom(other.Credit);
      }
      if (other.unitshard_ != null) {
        if (unitshard_ == null) {
          Unitshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard();
        }
        Unitshard.MergeFrom(other.Unitshard);
      }
      if (other.gearshard_ != null) {
        if (gearshard_ == null) {
          Gearshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard();
        }
        Gearshard.MergeFrom(other.Gearshard);
      }
      if (other.HasUnknown1) {
        Unknown1 = other.Unknown1;
      }
      if (other.HasUnknown2) {
        Unknown2 = other.Unknown2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (credit_ == null) {
              Credit = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit();
            }
            input.ReadMessage(Credit);
            break;
          }
          case 34: {
            if (unitshard_ == null) {
              Unitshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard();
            }
            input.ReadMessage(Unitshard);
            break;
          }
          case 106: {
            if (gearshard_ == null) {
              Gearshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard();
            }
            input.ReadMessage(Gearshard);
            break;
          }
          case 144: {
            Unknown1 = input.ReadInt64();
            break;
          }
          case 200: {
            Unknown2 = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (credit_ == null) {
              Credit = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductCredit();
            }
            input.ReadMessage(Credit);
            break;
          }
          case 34: {
            if (unitshard_ == null) {
              Unitshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductUnitshard();
            }
            input.ReadMessage(Unitshard);
            break;
          }
          case 106: {
            if (gearshard_ == null) {
              Gearshard = new global::SWGOH.Models.Protocols.StoreRpcBuyItemItemProductGearshard();
            }
            input.ReadMessage(Gearshard);
            break;
          }
          case 144: {
            Unknown1 = input.ReadInt64();
            break;
          }
          case 200: {
            Unknown2 = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemItemProductCredit : pb::IMessage<StoreRpcBuyItemItemProductCredit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemItemProductCredit> _parser = new pb::MessageParser<StoreRpcBuyItemItemProductCredit>(() => new StoreRpcBuyItemItemProductCredit());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemItemProductCredit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductCredit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductCredit(StoreRpcBuyItemItemProductCredit other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      quantity_ = other.quantity_;
      unknown_ = other.unknown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductCredit Clone() {
      return new StoreRpcBuyItemItemProductCredit(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static long NameDefaultValue = 1L;

    private long name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Name {
      get { if ((_hasBits0 & 1) != 0) { return name_; } else { return NameDefaultValue; } }
      set {
        _hasBits0 |= 1;
        name_ = value;
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private readonly static long QuantityDefaultValue = 0L;

    private long quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Quantity {
      get { if ((_hasBits0 & 2) != 0) { return quantity_; } else { return QuantityDefaultValue; } }
      set {
        _hasBits0 |= 2;
        quantity_ = value;
      }
    }
    /// <summary>Gets whether the "quantity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasQuantity {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "quantity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearQuantity() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "unknown" field.</summary>
    public const int UnknownFieldNumber = 3;
    private readonly static long UnknownDefaultValue = 0L;

    private long unknown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown {
      get { if ((_hasBits0 & 4) != 0) { return unknown_; } else { return UnknownDefaultValue; } }
      set {
        _hasBits0 |= 4;
        unknown_ = value;
      }
    }
    /// <summary>Gets whether the "unknown" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "unknown" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemItemProductCredit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemItemProductCredit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Quantity != other.Quantity) return false;
      if (Unknown != other.Unknown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasQuantity) hash ^= Quantity.GetHashCode();
      if (HasUnknown) hash ^= Unknown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(8);
        output.WriteInt64(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(8);
        output.WriteInt64(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Name);
      }
      if (HasQuantity) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (HasUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemItemProductCredit other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasQuantity) {
        Quantity = other.Quantity;
      }
      if (other.HasUnknown) {
        Unknown = other.Unknown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Name = input.ReadInt64();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Name = input.ReadInt64();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemItemProductUnitshard : pb::IMessage<StoreRpcBuyItemItemProductUnitshard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemItemProductUnitshard> _parser = new pb::MessageParser<StoreRpcBuyItemItemProductUnitshard>(() => new StoreRpcBuyItemItemProductUnitshard());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemItemProductUnitshard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductUnitshard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductUnitshard(StoreRpcBuyItemItemProductUnitshard other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      quantity_ = other.quantity_;
      unknown_ = other.unknown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductUnitshard Clone() {
      return new StoreRpcBuyItemItemProductUnitshard(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private readonly static long QuantityDefaultValue = 0L;

    private long quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Quantity {
      get { if ((_hasBits0 & 1) != 0) { return quantity_; } else { return QuantityDefaultValue; } }
      set {
        _hasBits0 |= 1;
        quantity_ = value;
      }
    }
    /// <summary>Gets whether the "quantity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasQuantity {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "quantity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearQuantity() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "unknown" field.</summary>
    public const int UnknownFieldNumber = 3;
    private readonly static long UnknownDefaultValue = 0L;

    private long unknown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown {
      get { if ((_hasBits0 & 2) != 0) { return unknown_; } else { return UnknownDefaultValue; } }
      set {
        _hasBits0 |= 2;
        unknown_ = value;
      }
    }
    /// <summary>Gets whether the "unknown" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "unknown" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemItemProductUnitshard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemItemProductUnitshard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Quantity != other.Quantity) return false;
      if (Unknown != other.Unknown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasQuantity) hash ^= Quantity.GetHashCode();
      if (HasUnknown) hash ^= Unknown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasQuantity) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (HasUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemItemProductUnitshard other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasQuantity) {
        Quantity = other.Quantity;
      }
      if (other.HasUnknown) {
        Unknown = other.Unknown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemItemProductGearshard : pb::IMessage<StoreRpcBuyItemItemProductGearshard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemItemProductGearshard> _parser = new pb::MessageParser<StoreRpcBuyItemItemProductGearshard>(() => new StoreRpcBuyItemItemProductGearshard());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemItemProductGearshard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductGearshard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductGearshard(StoreRpcBuyItemItemProductGearshard other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      quantity_ = other.quantity_;
      unknown_ = other.unknown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemItemProductGearshard Clone() {
      return new StoreRpcBuyItemItemProductGearshard(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private readonly static long QuantityDefaultValue = 0L;

    private long quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Quantity {
      get { if ((_hasBits0 & 1) != 0) { return quantity_; } else { return QuantityDefaultValue; } }
      set {
        _hasBits0 |= 1;
        quantity_ = value;
      }
    }
    /// <summary>Gets whether the "quantity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasQuantity {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "quantity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearQuantity() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "unknown" field.</summary>
    public const int UnknownFieldNumber = 3;
    private readonly static long UnknownDefaultValue = 0L;

    private long unknown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Unknown {
      get { if ((_hasBits0 & 2) != 0) { return unknown_; } else { return UnknownDefaultValue; } }
      set {
        _hasBits0 |= 2;
        unknown_ = value;
      }
    }
    /// <summary>Gets whether the "unknown" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUnknown {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "unknown" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUnknown() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemItemProductGearshard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemItemProductGearshard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Quantity != other.Quantity) return false;
      if (Unknown != other.Unknown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasQuantity) hash ^= Quantity.GetHashCode();
      if (HasUnknown) hash ^= Unknown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasQuantity) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (HasUnknown) {
        output.WriteRawTag(24);
        output.WriteInt64(Unknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasQuantity) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (HasUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemItemProductGearshard other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasQuantity) {
        Quantity = other.Quantity;
      }
      if (other.HasUnknown) {
        Unknown = other.Unknown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 24: {
            Unknown = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StoreRpcBuyItemPlayer : pb::IMessage<StoreRpcBuyItemPlayer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemPlayer> _parser = new pb::MessageParser<StoreRpcBuyItemPlayer>(() => new StoreRpcBuyItemPlayer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemPlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemResponseReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemPlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemPlayer(StoreRpcBuyItemPlayer other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemPlayer Clone() {
      return new StoreRpcBuyItemPlayer(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 7;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemPlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemPlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemPlayer other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 58: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 58: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
