// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StoreRpcBuyItemRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SWGOH.Models.Protocols {

  /// <summary>Holder for reflection information generated from StoreRpcBuyItemRequest.proto</summary>
  public static partial class StoreRpcBuyItemRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for StoreRpcBuyItemRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StoreRpcBuyItemRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxTdG9yZVJwY0J1eUl0ZW1SZXF1ZXN0LnByb3RvEhZTV0dPSC5Nb2RlbHMu",
            "UHJvdG9jb2xzInoKFlN0b3JlUnBjQnV5SXRlbVJlcXVlc3QSKgoNYnV5X2l0",
            "ZW1fbmFtZRgBIAEoCToTcHJlbWl1bS1wYWNrLXNpbHZlchIXCgxidXlfaXRl",
            "bV9rZXkYAiABKAM6ATQSGwoQYnV5X2l0ZW1fdW5rbm93bhgJIAEoAzoBMQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SWGOH.Models.Protocols.StoreRpcBuyItemRequest), global::SWGOH.Models.Protocols.StoreRpcBuyItemRequest.Parser, new[]{ "BuyItemName", "BuyItemKey", "BuyItemUnknown" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StoreRpcBuyItemRequest : pb::IMessage<StoreRpcBuyItemRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreRpcBuyItemRequest> _parser = new pb::MessageParser<StoreRpcBuyItemRequest>(() => new StoreRpcBuyItemRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StoreRpcBuyItemRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SWGOH.Models.Protocols.StoreRpcBuyItemRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemRequest(StoreRpcBuyItemRequest other) : this() {
      _hasBits0 = other._hasBits0;
      buyItemName_ = other.buyItemName_;
      buyItemKey_ = other.buyItemKey_;
      buyItemUnknown_ = other.buyItemUnknown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StoreRpcBuyItemRequest Clone() {
      return new StoreRpcBuyItemRequest(this);
    }

    /// <summary>Field number for the "buy_item_name" field.</summary>
    public const int BuyItemNameFieldNumber = 1;
    private readonly static string BuyItemNameDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("cHJlbWl1bS1wYWNrLXNpbHZlcg=="), 0, 19);

    private string buyItemName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BuyItemName {
      get { return buyItemName_ ?? BuyItemNameDefaultValue; }
      set {
        buyItemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "buy_item_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBuyItemName {
      get { return buyItemName_ != null; }
    }
    /// <summary>Clears the value of the "buy_item_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBuyItemName() {
      buyItemName_ = null;
    }

    /// <summary>Field number for the "buy_item_key" field.</summary>
    public const int BuyItemKeyFieldNumber = 2;
    private readonly static long BuyItemKeyDefaultValue = 4L;

    private long buyItemKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BuyItemKey {
      get { if ((_hasBits0 & 1) != 0) { return buyItemKey_; } else { return BuyItemKeyDefaultValue; } }
      set {
        _hasBits0 |= 1;
        buyItemKey_ = value;
      }
    }
    /// <summary>Gets whether the "buy_item_key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBuyItemKey {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "buy_item_key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBuyItemKey() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "buy_item_unknown" field.</summary>
    public const int BuyItemUnknownFieldNumber = 9;
    private readonly static long BuyItemUnknownDefaultValue = 1L;

    private long buyItemUnknown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BuyItemUnknown {
      get { if ((_hasBits0 & 2) != 0) { return buyItemUnknown_; } else { return BuyItemUnknownDefaultValue; } }
      set {
        _hasBits0 |= 2;
        buyItemUnknown_ = value;
      }
    }
    /// <summary>Gets whether the "buy_item_unknown" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBuyItemUnknown {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "buy_item_unknown" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBuyItemUnknown() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StoreRpcBuyItemRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StoreRpcBuyItemRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BuyItemName != other.BuyItemName) return false;
      if (BuyItemKey != other.BuyItemKey) return false;
      if (BuyItemUnknown != other.BuyItemUnknown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBuyItemName) hash ^= BuyItemName.GetHashCode();
      if (HasBuyItemKey) hash ^= BuyItemKey.GetHashCode();
      if (HasBuyItemUnknown) hash ^= BuyItemUnknown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBuyItemName) {
        output.WriteRawTag(10);
        output.WriteString(BuyItemName);
      }
      if (HasBuyItemKey) {
        output.WriteRawTag(16);
        output.WriteInt64(BuyItemKey);
      }
      if (HasBuyItemUnknown) {
        output.WriteRawTag(72);
        output.WriteInt64(BuyItemUnknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBuyItemName) {
        output.WriteRawTag(10);
        output.WriteString(BuyItemName);
      }
      if (HasBuyItemKey) {
        output.WriteRawTag(16);
        output.WriteInt64(BuyItemKey);
      }
      if (HasBuyItemUnknown) {
        output.WriteRawTag(72);
        output.WriteInt64(BuyItemUnknown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasBuyItemName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuyItemName);
      }
      if (HasBuyItemKey) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BuyItemKey);
      }
      if (HasBuyItemUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BuyItemUnknown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StoreRpcBuyItemRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasBuyItemName) {
        BuyItemName = other.BuyItemName;
      }
      if (other.HasBuyItemKey) {
        BuyItemKey = other.BuyItemKey;
      }
      if (other.HasBuyItemUnknown) {
        BuyItemUnknown = other.BuyItemUnknown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BuyItemName = input.ReadString();
            break;
          }
          case 16: {
            BuyItemKey = input.ReadInt64();
            break;
          }
          case 72: {
            BuyItemUnknown = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BuyItemName = input.ReadString();
            break;
          }
          case 16: {
            BuyItemKey = input.ReadInt64();
            break;
          }
          case 72: {
            BuyItemUnknown = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
